### ISSUE TITLE
Bluez speaker support

### ISSUE THREAD

**Issue by PraneetKaur** [FSMaxB/lfs-me-repos#1]
Hi,
Will bluez4.101 support external bluetooth speaker with A2Dp profile?

**Comment by FSMaxB** [comment]
How should I know?

This repository is mostly for documenting how I used [lfs-me](https://github.com/FSMaxB/lfs-me) to buid a [Linux From Scratch](http://www.linuxfromscratch.org/) system. More for inspiration than for actually using it yourself, and it hasn't been updated since LFS 7.6.

**Comment by PraneetKaur** [comment]
Thank you!
